import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import { getMetadata } from "./components/Header/MetaData/metadata";

const inter = Inter({ subsets: ["latin"] });


// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };
 export const metadata = getMetadata(
		"Dynamic Page Title",
		"Dynamic description based on the content of the page."
 );

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Header />
				{children}
			</body>
		</html>
	);
}
